spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: artikris50@gmail.com
    password: hjkjkjkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
    default-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/mysqldbd
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:7001}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  flyway:
    baseline-on-migrate: true
server:
  port: 8080






#   Email sender
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=artikris50@gmail.com
#  spring.mail.password=****your password*****
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true

